live_config_reload = true

[colors.bright]
black = "#3c3836"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#928374"
yellow = "#fabd2f"

[colors.cursor]
cursor = "@COLOR_LAYER2_FOREGROUND@"
text = "@COLOR_LAYER2_BACKGROUND@"

[colors.normal]
black = "#3c3836"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#928374"
yellow = "#fabd2f"

[colors.primary]
background = "@COLOR_LAYER2_BACKGROUND@"
foreground = "@COLOR_LAYER2_FOREGROUND@"

[font]
size = 11.0

[font.bold]
family = "@FONT_MONOSPACE@"
style = "Bold"

[font.bold_italic]
family = "@FONT_MONOSPACE@"
style = "Bold Italic"

[font.italic]
family = "@FONT_MONOSPACE@"
style = "Italic"

[font.normal]
family = "@FONT_MONOSPACE@"
style = "Regular"

[scrolling]
history = 10000
multiplier = 1

[window]
decorations = "full"

[window.padding]
x = 24
y = 24
