# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-f1587d91-a619-4191-bd19-86004696a0bd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices = {
    "luks-f1587d91-a619-4191-bd19-86004696a0bd".device =
      "/dev/disk/by-uuid/f1587d91-a619-4191-bd19-86004696a0bd";
    "luks-07d30502-e311-4170-a3ce-441116bda61b".device =
      "/dev/disk/by-uuid/07d30502-e311-4170-a3ce-441116bda61b";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F318-F30D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-07d30502-e311-4170-a3ce-441116bda61b"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
