"$schema" = 'https://starship.rs/config-schema.json'

# Print a newline before the prompt
add_newline = true

# Only use specific modules
format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $nix_shell\
  $aws\
  $terraform\
  $cmd_duration\
  $status\
  $line_break\
  $character"""

[character]
format = "[\\$](bold green) "

[cmd_duration]
min_time = 1_000
show_notifications = false

[directory]
format = "[$path/]($style) "
truncation_length = 8
truncate_to_repo = false
truncation_symbol = ".../"

[git_status]
format = "[$ahead_behind]($style)"
ahead = "[⇡ ${count}](green) "
behind = "[⇣ ${count}](red) "
diverged = "[⇡ ${ahead_count} ⇕ ⇣ ${behind_count}](yellow) "

[nix_shell]
format = "via [$symbol Nix]($style) "
heuristic = true
symbol = "❄️"

[status]
format = "[$symbol $status]($style) "
symbol = "⚠"
disabled = false
